services:
  - type: web
    name: your-site
    buildCommand: npm install && npm run build
    staticPublishPath: "./dist"
    headers:
      - path: "/*.js"
        name: "Content-Type"
        value: "text/javascript"